"""add is reserve for sale

Revision ID: 243e4f492ee3
Revises: 8dc700504261
Create Date: 2024-08-30 11:38:38.640029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243e4f492ee3'
down_revision: Union[str, None] = '8dc700504261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('is_reserve', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'is_reserve')
    # ### end Alembic commands ###
