"""add promotion status

Revision ID: 6e90f9b9ef67
Revises: 4881725b70dc
Create Date: 2024-08-29 12:58:55.243729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e90f9b9ef67'
down_revision: Union[str, None] = '4881725b70dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('status', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_promotions_status'), 'promotions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotions_status'), table_name='promotions')
    op.drop_column('promotions', 'status')
    # ### end Alembic commands ###
