"""add discount for sale table

Revision ID: 8dc700504261
Revises: 6e90f9b9ef67
Create Date: 2024-08-30 11:24:58.489991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc700504261'
down_revision: Union[str, None] = '6e90f9b9ef67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('full_price', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('sold_price', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('discount_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'discount_percentage')
    op.drop_column('sales', 'sold_price')
    op.drop_column('sales', 'full_price')
    # ### end Alembic commands ###
